import { useEffect } from "react";
import { auth, db } from "../firebase";
import { writeBatch, addDoc, doc, collection, setDoc, getDocs, query, where, documentId, updateDoc, increment, getDoc } from "firebase/firestore";

export default function Home() {
  const collectionRef = collection(db, "quotes");

  const arr = [
    "Own the room. Own your story. Own your life.",
    "You are not a side character in your own story---act like it.",
    "Confidence isn't given; it's built through action.",
    "Your potential is greater than your current reality.",
    "Doubt kills more dreams than failure ever could.",
    "Your self-worth isn't up for negotiation.",
    "Talk to yourself like you would to someone you love.",
    "The loudest voice in your head should be your own belief.",
    "You were made for more---start acting like it.",
    "The world sees you how you see yourself.",
    "The way you see yourself determines what you allow yourself to become.",
    "You are capable of far more than you’ve ever dared to believe.",
    "Your belief in yourself sets the limits of your reality.",
    "If you don’t bet on yourself, why should anyone else?",
    "You don’t need permission to be great—just the courage to act.",
    "Doubt is the thief of possibility—don’t let it win.",
    "You’re not behind. You’re exactly where you need to be to grow into your next level.",
    "Confidence isn’t knowing you’ll win—it’s knowing you can handle whatever happens.",
    "The moment you stop doubting yourself, the world starts believing in you.",
    "Your self-worth isn’t up for negotiation.",
    "Fear exists to test your commitment to yourself.",
    "Self-doubt is a liar—don’t listen.",
    "The only thing standing between you and your dreams is the story you tell yourself.",
    "You weren’t put on this earth to shrink—you were made to shine.",
    "Confidence is built, not given.",
    "You don’t have to be fearless. You just have to act in spite of the fear.",
    "Stop waiting for validation—your belief in yourself is enough.",
    "If you keep underestimating yourself, you’ll never know what you’re truly capable of.",
    "You have survived every single challenge life has thrown at you—why doubt yourself now?",
    "The mind can be your prison or your power—choose wisely.",
    "Once you realize your worth, no one can make you feel worthless.",
    "Confidence is not about arrogance—it’s about certainty in your ability to handle anything.",
    "You are not obligated to be the person others expect you to be.",
    "They doubted you? Good. Now prove them wrong.",
    "When you trust yourself, the world adjusts accordingly.",
    "You were built for this—stop acting like you weren’t.",
    "Strength isn’t found, it’s forged through self-belief.",
    "The more you show up for yourself, the less you need validation from others.",
    "You don’t need luck when you have unshakable belief in yourself.",
    "Once you start believing in yourself, you become unstoppable.",
    "You are already enough—act like it.",
    "Confidence is the loudest when it doesn’t need to prove itself.",
    "Your worth is not measured by other people’s opinions.",
    "You don’t have to prove yourself to people who don’t see your value.",
    "If you knew your true power, you’d never doubt yourself again.",
    "Stop trying to fit in—you weren’t meant to.",
    "Never let someone else’s insecurities shake your confidence.",
    "Your value doesn’t decrease based on someone’s inability to see it.",
    "Believe in yourself so strongly that the world has no choice but to believe in you too.",
    "The most powerful thing you can be is unapologetically yourself.",
    "Self-doubt doesn’t mean you’re weak—it means you’re growing past your comfort zone.",
    "The only way to silence self-doubt is through action.",
    "Confidence isn’t pretending to be fearless—it’s trusting yourself despite the fear.",
    "The opinions that hold you back the most are the ones inside your own head.",
    "You’re either feeding your confidence or your insecurities—choose wisely.",
    "The day you stop doubting yourself is the day everything changes.",
    "Even your flaws make you unique—own them.",
    "Talk to yourself the way you would encourage a friend.",
    "Replace self-doubt with self-trust.",
    "You are more powerful than the voice in your head telling you otherwise.",
    "Confidence is the bridge between dreams and reality.",
    "Start before you’re ready—confidence is built in action, not in waiting.",
    "Your hesitation is costing you more than your failure ever could.",
    "Stop preparing, start doing.",
    "Confidence grows when you keep the promises you make to yourself.",
    "Perfection isn’t required—bold action is.",
    "Trust yourself enough to take the first step.",
    "Every time you show up, you prove to yourself that you can.",
    "You don’t become confident and then take action. You take action and become confident.",
    "Start acting like the person you want to become.",
    "You weren’t given this vision for no reason—trust it.",
    "Your future self is watching—give them something to be proud of.",
    "No one is coming to save you—be your own hero.",
    "You already have everything you need to succeed—you just need to believe it.",
    "Stop waiting for the stars to align—be the force that moves them.",
    "Greatness doesn’t ask for permission.",
    "The biggest breakthroughs happen the moment you stop doubting yourself.",
    "Confidence isn’t about knowing you’ll win—it’s knowing you can handle losing.",
    "If you don’t back yourself, who will?",
    "Own your potential or waste it—your choice.",
    "The only limits that exist are the ones you accept.",
    "You’re not stuck—you’re just hesitating to take the next step.",
    "Other people’s limits are not your reality.",
    "You weren’t born to be mediocre.",
    "There is no ceiling—only the limits you choose to believe in.",
    "Stop lowering your standards to make others comfortable.",
    "You will never regret betting on yourself.",
    "Confidence isn’t about knowing everything—it’s about trusting yourself to figure it out.",
    "If you want to be limitless, stop playing small.",
    "You didn’t come this far just to doubt yourself now.",
    "Self-belief is a muscle—train it daily.",
    "If you can’t trust yourself, how can you expect others to?",
    "Confidence isn’t something you find—it’s something you decide.",
    "Act like you belong in every room you walk into.",
    "The most dangerous person in the room is the one who truly believes in themselves.",
    "The moment you trust yourself, everything shifts.",
    "Confidence is about embracing who you are, not proving who you aren’t.",
    "Your self-trust is more important than anyone else’s approval.",
    "Believe in yourself the way you believe in others.",
    "Once you stop questioning your own value, the world follows suit.",
    "Adversity introduces you to your true self.",
    "Your struggles are the chapters of your comeback story.",
    "Tough times don't last, but tough people do.",
    "The storm will pass, but the strength you gain will stay.",
    "Resilience is built in the moments no one sees.",
    "Turn every setback into a setup for something greater.",
    "Survival mode is temporary---build mode is forever.",
    "Every wound carries wisdom---learn from it.",
    "Pain is temporary, but quitting lasts forever.",
    "You didn't come this far just to come this far.",
    "Hard times test you, but they also build you.",
    "Nothing can break you if you refuse to stay broken.",
    "Your lowest points are the foundations of your strength.",
    "Storms don't last forever, but strong people do.",
    "Turn your pain into power.",
    "Don't let failures make you forget how far you've come.",
    "Resilience is built in the struggle.",
    "Fall seven times, rise eight.",
    "The longer the wait, the greater the reward.",
    "Tough times reveal who you truly are.",
    "Diamonds are made under pressure---so are you.",
    "Every battle scars you, but also strengthens you.",
    "You've survived % of your worst days.",
    "Adversity is life's way of testing your commitment.",
    "Your struggles today build your strength for tomorrow.",
    "Greatness is built in the fire of challenges.",
    "When life hits hard, hit back harder.",
    "Resilience is built in the moments no one sees.",
    "There's no growth without resistance.",
    "Failure is proof you're trying. Keep going.",
    "Storms reveal the strength of the roots, not the branches.",
    "Your past is a chapter, not the whole book.",
    "You weren't given this mountain to admire it---you were meant to climb it.",
    "Success is built on the bricks of failure.",
    "Hard times don't last, but hard people do.",
    "Pain refines. Struggle sharpens. Growth transforms.",
    "Adversity introduces you to yourself.",
    "A scar is proof that you healed, not that you were broken.",
    "The comeback is always stronger than the setback.",
    "Never let a hard moment make you forget who you are.",
    "Tough times introduce you to your strongest self.",
    "A setback is a setup for your greatest comeback.",
    "You haven’t come this far just to stop here.",
    "The storm you’re in is shaping the strength you need.",
    "Endurance beats talent when talent stops trying.",
    "Pain is the proof you’re alive—use it as fuel.",
    "Fall down seven times, stand up eight.",
    "There is no strength without struggle.",
    "You won’t always feel strong, but you can always act strong.",
    "The world doesn’t break the strong—it reveals them.",
    "Resilience isn’t about avoiding the storm—it’s about learning to dance in the rain.",
    "Strength isn’t found in ease; it’s forged in struggle.",
    "The world breaks everyone, but some rise stronger in the broken places.",
    "Every scar tells a story of survival.",
    "Resilience is built in the moments you refuse to give up.",
    "If you’ve made it this far, you can make it further.",
    "The only thing stronger than adversity is the person who refuses to quit.",
    "You weren’t given this challenge to break—you were given it to build.",
    "Bend, but never break.",
    "Resilience is simply refusing to be defined by failure.",
    "Pain is temporary—growth is forever.",
    "Every struggle has a purpose, even if you can’t see it yet.",
    "Your worst days are shaping your best ones.",
    "You don’t have to like the battle, but you do have to fight it.",
    "What you overcome today becomes your strength tomorrow.",
    "Survival is proof of strength.",
    "The road isn’t easy, but neither is regret.",
    "It’s okay to break—just don’t stay broken.",
    "Some of the strongest people are the ones no one saw struggling.",
    "Adversity introduces you to the version of yourself you were meant to be.",
    "Strength is silent; resilience is loud.",
    "You are stronger than what’s trying to break you.",
    "Nothing can truly defeat you unless you let it.",
    "You can bend under pressure, but never let it shape you into something lesser.",
    "Weakness is not falling—it’s refusing to get back up.",
    "A resilient mind can turn rock bottom into a foundation.",
    "Some people run from fire, others walk through it and come out stronger.",
    "Keep moving, even if all you can do is crawl.",
    "Resilience is a decision, not a trait.",
    "Tough times don’t last—tough people do.",
    "Your struggle is the blueprint of your strength.",
    "The fire that burns you can also forge you.",
    "Every difficulty carries the seed of greater strength.",
    "Use your scars as fuel, not excuses.",
    "Your ability to endure is your greatest weapon.",
    "No one said it would be easy, but nothing worth having ever is.",
    "You don’t need to be fearless—just unbreakable.",
    "The pressure you’re under is shaping you, not breaking you.",
    "Resilience is refusing to let circumstances decide your fate.",
    "Growth happens when you keep going despite every reason to stop.",
    "You are more powerful than the hardships you’ve faced.",
    "A strong spirit bends but never shatters.",
    "Strength isn’t loud—it’s in the quiet moments of perseverance.",
    "Life may test you, but you always have the final answer.",
    "The strongest people don’t have easy pasts.",
    "Your limits are further than you think—keep pushing.",
    "Everything you’ve survived has made you unshakable.",
    "No one can take away your strength—it’s yours to own.",
    "The road is rough, but so are you.",
    "Your resilience is the loudest proof of your power.",
    "Discipline is self-love in action.",
    "Consistency is more powerful than intensity.",
    "You don't need motivation when you have systems.",
    "Every habit is a vote for the person you want to become.",
    "Discipline turns intentions into results.",
    "If you can master your habits, you can master anything.",
    "Success is hidden in your daily routine.",
    "What you do repeatedly shapes who you are.",
    "Your habits either make you or break you---choose wisely.",
    "Stay disciplined long enough, and the results will shock you.",
    "Discipline is freedom in disguise.",
    "Your habits determine your future, not your wishes.",
    "Success is simply a series of good habits repeated daily.",
    "Willpower fades; discipline lasts.",
    "Every action you take is a vote for who you become.",
    "You don't need motivation when you have discipline.",
    "The gap between who you are and who you want to be is filled with habits.",
    "The compound effect of small habits creates massive change.",
    "What you do daily matters more than what you do once in a while.",
    "Discipline makes success inevitable.",
    "Your habits write the story of your future.",
    "Discipline is the foundation of all achievement.",
    "Success is hidden in your daily routine.",
    "Consistency is the secret ingredient to greatness.",
    "Wake up with discipline; go to bed with progress.",
    "The more disciplined you become, the easier life gets.",
    "What you do in private shows in public.",
    "Results don't come from wishes, but from habits.",
    "Your future self is watching---don't disappoint them.",
    "Discipline beats motivation every time.",
    "Your habits shape your future---choose them wisely.",
    "Discipline is the bridge between goals and achievement.",
    "Don't wait for motivation. Build discipline instead.",
    "Tiny habits create massive results over time.",
    "Your morning routine sets the tone for your entire day.",
    "Your future is hidden in your daily routine.",
    "The difference between a dream and a reality is execution.",
    "Consistency will take you further than talent ever could.",
    "You are what you repeatedly do.",
    "Your actions prove what you truly want, not your words.",
    "Success is built in the small decisions nobody sees.",
    "Your habits decide your future, not your goals.",
    "You don’t need motivation. You need consistency.",
    "Your time is your most honest investment.",
    "What you do daily is what you become permanently.",
    "Every habit is a vote for the person you want to be.",
    "The most successful people are just the most consistent.",
    "Momentum is built in the days you don’t feel like showing up.",
    "How you do anything is how you do everything.",
    "Small daily wins become unstoppable momentum.",
    "Discipline is choosing between what you want now and what you want most.",
    "The secret of success is discipline. If you can master yourself, you can master anything.",
    "Without discipline, talent is just potential waiting to be wasted.",
    "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
    "A disciplined mind leads to a disciplined life.",
    "Your level of discipline determines the height of your success.",
    "Self-discipline is the key to unlocking your full potential.",
    "Discipline is the foundation of all great achievements.",
    "The pain of discipline is temporary, but the regret of neglect lasts forever.",
    "Discipline is not about punishment; it’s about training yourself for greatness.",
    "We are what we repeatedly do. Excellence, then, is not an act but a habit. – Aristotle",
    "Your habits create your future—choose them wisely.",
    "Small habits, when repeated daily, create extraordinary results.",
    "Success is nothing more than a few simple disciplines practiced every day. – Jim Rohn",
    "Your future is hidden in your daily routine.",
    "The habits you build today will shape the life you live tomorrow.",
    "You don’t rise to the level of your goals; you fall to the level of your habits. – James Clear",
    "Habits are the invisible architecture of your life.",
    "Good habits are the key to success, bad habits are the door to failure.",
    "What you do daily matters more than what you do occasionally.",
    "Discipline is the mother of good habits.",
    "Good habits, fueled by discipline, create unstoppable momentum.",
    "Discipline shapes habits, and habits shape destiny.",
    "Without discipline, even the best habits fade away.",
    "Habits make success automatic, but discipline starts the engine.",
    "Every disciplined habit you build adds another brick to your dreams.",
    "It takes discipline to build habits and habits to maintain discipline.",
    "The road to success is paved with discipline and reinforced with habits.",
    "Your habits whisper your future before you even get there.",
    "Discipline is the seed, habits are the roots, and success is the tree.",
    "One disciplined decision at a time creates a lifetime of success.",
    "If you don’t discipline yourself, the world will do it for you.",
    "Master your habits, or they will master you.",
    "Discipline turns dreams into realities, one habit at a time.",
    "Winning is a habit, but so is losing. Choose wisely.",
    "Small disciplines practiced daily lead to massive successes over time.",
    "Your habits should work for you, not against you.",
    "Don’t wait for motivation—use discipline and let habits take over.",
    "The disciplined create their own luck through consistent effort.",
    "Habits don’t change overnight, but overnight habits change lives.",
    "Discipline and habits are the silent architects of character.",
    "The most powerful form of self-respect is self-discipline.",
    "If you master discipline and habits, you master life itself.",
    "Freedom comes from discipline, not from indulgence.",
    "The chains of habit are too weak to be felt until they are too strong to be broken. – Samuel Johnson",
    "Your habits reflect your values more than your words ever will.",
    "A life of discipline leads to a life of freedom.",
    "The disciplined mind creates a disciplined world.",
    "Success is built in silence, through disciplined habits no one sees.",
    "Greatness is not a matter of chance; it is a matter of disciplined choice.",
    "Fear is just excitement in disguise---lean into it.",
    "Feel the fear and do it anyway.",
    "Your dreams live outside your comfort zone.",
    "Fear is a compass pointing you toward growth.",
    "If you never take the leap, you'll never know how high you can fly.",
    "Courage is built in the moments no one sees.",
    "Playing it safe is the riskiest move of all.",
    "The only thing scarier than failure is regret.",
    "Fear is temporary. Regret lasts forever.",
    "Don't let doubt write your story.",
    "Fear is a liar---prove it wrong.",
    "If it scares you, it's probably worth doing.",
    "The only way past fear is through it.",
    "Your comfort zone is your prison.",
    "Fear fades when action begins.",
    "Your future self is waiting on your courage today.",
    "If you never take risks, you'll never know your full potential.",
    "Courage is built in the moments when no one is watching.",
    "Dare to fail big, and you'll succeed even bigger.",
    "You can either let fear stop you or fuel you---choose wisely.",
    "Fear is just excitement without direction.",
    "Do it afraid. Do it uncertain. Just do it.",
    "Your courage builds the life you dream of.",
    "Fear disappears the moment you take action.",
    "Bravery isn't the absence of fear, but action despite it.",
    "Most fears are illusions---walk through them.",
    "Stop waiting for permission---start now.",
    "Fear is a thief. Take back what's yours.",
    "The boldest moves create the biggest rewards.",
    "The cost of playing it safe is never knowing your potential.",
    "Run towards what scares you---the reward is on the other side.",
    "Fear is a liar. Action exposes the truth.",
    "If you're afraid to fail, you'll never learn to fly.",
    "Being scared means you're on the edge of growth. Keep going.",
    "Your fear is not stronger than your purpose.",
    "Feel the fear. Do it anyway.",
    "You were brave before you were ready.",
    "Daring greatly leads to living fully.",
    "Courage is being terrified but moving forward anyway.",
    "Your future self will thank you for being bold today.",
    "Your fears are only as powerful as your willingness to obey them.",
    "A life led by fear is a life unlived.",
    "The only way to silence fear is to take action.",
    "Fear is a liar that sounds convincing.",
    "The hardest step is the first. Take it anyway.",
    "Everything you want is on the other side of fear.",
    "Fear shrinks when you move toward it.",
    "If it scares you, it’s probably worth doing.",
    "Your courage is built in moments of uncertainty.",
    "Fear is a signpost, not a stop sign.",
    "Fear is a shadow that only exists when you turn away from the light.",
    "The scariest paths often lead to the most beautiful destinations.",
    "Fear is the mind’s way of testing how badly you want something.",
    "Most fears are just stories we tell ourselves—rewrite the narrative.",
    "Fear thrives on hesitation; action is its greatest enemy.",
    "What you fear most is often the key to your greatest breakthrough.",
    "Fear whispers to stop, but regret screams louder.",
    "The weight of fear is always heavier than the weight of trying.",
    "Fear is the gatekeeper of growth—face it to move forward.",
    "Let fear be your compass, not your cage.",
    "Courage is not the absence of fear but the decision to keep moving despite it.",
    "Bravery is just fear wrapped in determination.",
    "Courage begins the moment you refuse to let fear make your choices.",
    "The smallest act of courage can shatter the biggest wall of fear.",
    "You don’t have to be fearless, just willing to take the next step.",
    "Courage is the fuel that turns dreams into reality.",
    "Bravery isn’t loud; it’s often just a quiet step forward.",
    "Courage is built in moments of doubt, not moments of ease.",
    "A single act of courage can change the course of your entire life.",
    "Fear says ‘what if?’ Courage says ‘why not?’",
    "Fear builds walls, courage builds bridges.",
    "Fear sees the risk, courage sees the reward.",
    "Courage is fear that has learned how to walk.",
    "Fear makes excuses, courage makes progress.",
    "Fear will paralyze you, but courage will set you free.",
    "Courage isn’t about being unafraid; it’s about choosing to act anyway.",
    "Fear questions everything; courage answers with action.",
    "Where fear ends, courage begins.",
    "Fear wants you to stay the same; courage dares you to grow.",
    "Every great story begins with a moment of fear and a choice for courage.",
    "Fear only controls you if you let it sit in the driver’s seat.",
    "Face your fears enough times, and they’ll start fearing you.",
    "The only way to silence fear is to walk straight through it.",
    "Fear fades when met with relentless action.",
    "Your fear of failure should never be stronger than your desire to succeed.",
    "Most fears dissolve the moment you take the first step.",
    "Fear is temporary, but the regret of not trying lasts forever.",
    "Doubt kills more dreams than fear ever could.",
    "Run from fear, and it grows. Chase fear, and it shrinks.",
    "You don’t conquer fear by avoiding it—you conquer it by proving it wrong.",
    "Courage isn’t just for heroes; it’s for anyone willing to try.",
    "A brave heart beats louder than a fearful mind.",
    "Courage isn’t about winning, it’s about standing up even when you might lose.",
    "Fear limits life; courage expands it.",
    "Every day is a choice—fear or courage. Choose wisely.",
    "Live boldly, for fear will never tell a great story.",
    "The strongest people are those who have danced with fear and chosen courage.",
    "Bravery is a habit—build it one decision at a time.",
    "You are braver than your worst day and stronger than your biggest fear.",
    "Fear knocks, but courage is the one who opens the door.",
    "Great leaders don't demand respect---they earn it.",
    "True leadership starts with self-mastery.",
    "Your influence is measured by the lives you impact.",
    "Lead with vision, serve with heart, and success will follow.",
    "A leader's strength is in their ability to empower others.",
    "People don't follow titles; they follow courage.",
    "The best leaders don't compete---they create.",
    "To inspire others, first inspire yourself.",
    "A true leader doesn't seek power---they seek impact.",
    "Lead in a way that makes others want to rise.",
    "A true leader doesn't create followers, but more leaders.",
    "Your influence is measured by how many people you empower.",
    "Leaders don't wait for permission to take action.",
    "People follow consistency more than words.",
    "Great leaders serve first, then lead.",
    "Be the type of person you'd want to follow.",
    "Leadership is action, not position.",
    "The best way to lead is by example.",
    "Your legacy is built through your impact, not your title.",
    "Leaders make decisions; followers wait for them.",
    "Lead by example, not by words.",
    "Your impact is measured by those you lift up.",
    "Leaders don't create followers---they create leaders.",
    "True leadership is service, not status.",
    "People follow those who inspire action.",
    "You can't lead others if you can't lead yourself.",
    "Influence comes from integrity, not position.",
    "Your words shape the world around you.",
    "Power isn't given, it's earned through action.",
    "Be the type of leader you wish you had.",
    "A true leader creates more leaders, not followers.",
    "Your influence is measured by how many lives you improve.",
    "The best leaders listen twice as much as they speak.",
    "You don’t have to be in charge to lead.",
    "Confidence is silent. Insecurity is loud.",
    "Great leaders don’t demand respect—they earn it.",
    "Power isn’t about control—it’s about service.",
    "Your character is your loudest message.",
    "To inspire others, first inspire yourself.",
    "Your energy introduces you before your words do.",
    "A true leader doesn’t demand respect—they earn it through action.",
    "Leadership is not about power; it’s about purpose.",
    "The best leaders don’t create followers, they create more leaders.",
    "Leadership is not about being in charge; it’s about taking responsibility.",
    "A leader’s greatest strength is their ability to listen.",
    "Titles don’t make leaders—actions do.",
    "A leader’s success is measured by the success of those they lead.",
    "True leadership is serving, not ruling.",
    "A leader lights the way, not just walks ahead.",
    "The strongest leaders are those who lift others higher.",
    "Great leaders lead with both wisdom and humility.",
    "Leadership isn’t about being the loudest in the room, but the most impactful.",
    "The best leaders inspire through action, not instruction.",
    "Leadership is the art of making people believe in themselves.",
    "A leader’s legacy is written in the lives they change.",
    "Good leaders give orders. Great leaders inspire action.",
    "A true leader leads by example, not by ego.",
    "To lead well, you must first learn to follow.",
    "A leader’s job is to bring out the best in others, not to be the best themselves.",
    "Real leadership isn’t about control—it’s about empowerment.",
    "Influence is not about persuasion; it’s about inspiration.",
    "The most powerful leaders are those who influence without force.",
    "Your actions influence more than your words ever will.",
    "True influence isn’t about how many listen to you, but how many are changed by you.",
    "You don’t need authority to have influence—you need impact.",
    "Influence is earned through consistency, not commands.",
    "Real influence is felt, not forced.",
    "The greatest influencers lead with integrity, not manipulation.",
    "Your influence is measured by how many lives you touch.",
    "A single act of kindness can influence a lifetime.",
    "Leadership isn’t about being seen; it’s about making a difference.",
    "To influence others, first master yourself.",
    "Your influence extends beyond what you see—every small action matters.",
    "Great leaders influence by lifting, not by pushing.",
    "The impact of a leader is felt long after they are gone.",
    "Your influence is your legacy—build it wisely.",
    "True influence is built on trust, not tactics.",
    "Influence is not about convincing; it’s about demonstrating.",
    "People follow those who make them feel valued, not those who make them feel small.",
    "The strongest influence comes from authenticity, not authority.",
    "A leader’s influence is seen in the strength of those they lead.",
    "Leadership and influence are not about control, but about connection.",
    "A leader’s true power is in their ability to inspire action.",
    "Leaders influence not by force, but by example.",
    "The best leaders are those who influence through service, not status.",
    "Leadership is a privilege, not a position.",
    "Influence is the heart of leadership.",
    "A leader’s influence is not measured by how many follow them, but by how many grow because of them.",
    "Leaders create waves of influence that ripple beyond what they see.",
    "Every great leader was once an influenced follower.",
    "You can lead with words, but you influence with actions.",
    "The best leaders create a culture of influence, not fear.",
    "Leadership is about lighting the path, influence is about guiding the steps.",
    "Influence lasts longer than authority.",
    "A true leader’s influence is not forced; it is felt.",
    "The most influential leaders don’t seek attention, they create impact.",
    "Leaders shape minds; influencers shape hearts.",
    "Power fades, but influence endures.",
    "You don’t need a stage to lead; influence starts with one person at a time.",
    "Leadership is what you do; influence is how you do it.",
    "The right people bring out the best in you.",
    "Love isn't found---it's built.",
    "Loyalty isn't said, it's shown.",
    "Energy doesn't lie---trust the vibes.",
    "A real connection doesn't need validation---it's felt.",
    "Never chase someone who doesn't appreciate your presence.",
    "Love should make you grow, not shrink.",
    "The right love makes you feel seen, heard, and safe.",
    "Protect your peace---choose people who choose you.",
    "Strong relationships are built on trust, effort, and consistency.",
    "Choose people who choose you.",
    "Energy never lies---trust the vibes.",
    "The right people bring out the best in you.",
    "Love is an action, not just a feeling.",
    "Loyalty isn't a word---it's a lifestyle.",
    "A relationship should add to your peace, not take from it.",
    "Protect your heart from those who don't value it.",
    "Real love is felt, not just heard.",
    "Never beg for effort---it should be given freely.",
    "Strong relationships are built, not found.",
    "Love without action is just a word.",
    "The right people make you feel unstoppable.",
    "A real connection is worth more than a thousand followers.",
    "Strong relationships require effort, not just feelings.",
    "Love should make you grow, not shrink.",
    "Loyalty is rare---cherish those who show it.",
    "The energy between two people is everything.",
    "People remember how you made them feel.",
    "Be the partner you'd want to have.",
    "The strongest relationships are built on trust and action.",
    "Love deeply, not just conveniently.",
    "People remember how you made them feel, not what you said.",
    "The strongest relationships are built on trust, not words.",
    "True love is an action, not just a feeling.",
    "Love is not about finding the right person—it’s about being the right person.",
    "Loyalty isn’t proven in words, but in presence.",
    "The strongest relationships are built on truth, not comfort.",
    "Love is an action, not just a feeling.",
    "Give the love you wish to receive.",
    "Surround yourself with people who make your soul feel lighter.",
    "Real connection requires vulnerability, not perfection.",
    "You can’t love someone into becoming who they aren’t ready to be.",
    "The right people will never require you to shrink yourself.",
    "Your vibe attracts your tribe—choose wisely.",
    "Connection is the greatest currency.",
    "Surround yourself with those who lift, not limit.",
    "A team beats a lone wolf every time.",
    "Protect your energy from those who drain it.",
    "You become like the people you spend the most time with.",
    "Real connection is rare---cherish it when you find it.",
    "Love isn’t about finding the perfect person; it’s about seeing perfection in their imperfections.",
    "Real love isn’t measured in words but in the quiet moments of understanding.",
    "True love doesn’t complete you; it strengthens the person you already are.",
    "Love isn’t about possession; it’s about appreciation.",
    "A heart that loves deeply never loses its warmth, even in the coldest times.",
    "Love is the art of choosing someone, every single day.",
    "The purest love is found in the smallest gestures.",
    "A love that grows is a love that lasts.",
    "Love is not just about saying ‘I love you’; it’s about proving it through action.",
    "When love is real, distance and time mean nothing.",
    "A strong relationship isn’t built on grand moments, but on small, consistent acts of kindness.",
    "The best relationships are not about perfection, but about embracing imperfections together.",
    "A great relationship is where two people inspire each other to be better.",
    "Trust and communication are the foundation of every lasting relationship.",
    "In love, it’s not about who is right, but about what is right for the relationship.",
    "The happiest relationships are those where love and friendship walk hand in hand.",
    "A relationship thrives when both partners choose patience over pride.",
    "Love grows strongest in relationships that weather storms together.",
    "A true relationship is two imperfect people refusing to give up on each other.",
    "A relationship is not just about love, but about respect, trust, and shared dreams.",
    "Love doesn’t just happen; it’s nurtured through effort, care, and time.",
    "The strongest relationships are built on more than love—they are built on deep understanding.",
    "Love is not about needing someone; it’s about choosing them even when you don’t have to.",
    "A soulmate is not found, but recognized through the way they make your soul feel at home.",
    "Love isn’t about changing someone; it’s about growing together.",
    "Two hearts in sync don’t have to be the same, they just have to beat for each other.",
    "Love is when two souls find a way to understand each other beyond words.",
    "The right person doesn’t make life perfect, but they make every challenge worth facing.",
    "Love is when you find peace in someone’s presence.",
    "A love that is patient is a love that lasts.",
    "Love isn’t about never arguing; it’s about arguing and still choosing each other.",
    "Every relationship faces storms; the strongest ones learn how to dance in the rain.",
    "Love is not tested in happy times, but in the moments that require forgiveness.",
    "A relationship is strongest when both people fight for each other, not against each other.",
    "Real love is knowing someone’s flaws and choosing to stand beside them anyway.",
    "Distance tests love, but true love passes every test.",
    "A lasting relationship is not built on avoiding problems, but on facing them together.",
    "Love isn’t about avoiding conflict; it’s about working through it with respect.",
    "The deepest love is the one that grows through challenges, not avoids them.",
    "A love that forgives is a love that flourishes.",
    "Forever is built one loving moment at a time.",
    "The best love stories are written in everyday moments.",
    "Love doesn’t fade with time, it deepens when nurtured.",
    "The right person makes a lifetime feel like a beautiful moment.",
    "A heart that stays loyal is a heart that truly loves.",
    "Love is not just about saying ‘yes’ in the beginning, but about saying ‘yes’ every day after.",
    "The best kind of love is the one that still feels fresh even after years.",
    "Commitment is not about chains; it’s about the freedom of choosing love every day.",
    "A love that lasts is a love that evolves.",
    "The greatest love stories are not written in books, but in the way two people choose each other over and over again.",
    "How you see the world is how you experience it.",
    "You don't control the storm, but you control how you sail through it.",
    "Growth happens when you stop running from discomfort.",
    "Your perspective determines your reality.",
    "Sometimes, the lesson is hidden in the struggle.",
    "Peace comes when you stop arguing with reality.",
    "Not every battle is worth your energy.",
    "The ability to adapt is more valuable than any plan.",
    "A setback is often a setup for something greater.",
    "Some doors close because they were never meant for you.",
    "Your perception shapes your reality.",
    "Don't believe everything you think.",
    "The strongest minds question everything.",
    "Sometimes rejection is just redirection.",
    "The ability to adapt is the greatest skill.",
    "The quality of your thoughts determines the quality of your life.",
    "Growth happens when you challenge your own beliefs.",
    "See obstacles as teachers, not enemies.",
    "Not every battle is worth fighting.",
    "Wisdom is knowing when to speak and when to listen.",
    "You see what you focus on---choose wisely.",
    "Life doesn't get easier; you just get stronger.",
    "Not every battle is worth fighting.",
    "Perspective turns problems into lessons.",
    "If it won't matter in five years, don't waste five minutes on it.",
    "Learn to be happy with less, and you'll never feel lacking.",
    "Time is the only currency that never refunds.",
    "Growth starts when you ask better questions.",
    "Some doors close for your protection.",
    "A setback is often just a setup for a comeback.",
    "Your reality is shaped by the way you interpret it.",
    "You can't control the storm, but you can control how you sail through it.",
    "The world will tell you who you are. Ignore it and define yourself.",
    "You don't need all the answers; you just need curiosity.",
    "See obstacles as detours, not dead ends.",
    "The best way to predict the future is to create it.",
    "Let go of what you can't change. Master what you can.",
    "Everything is a lesson if you're paying attention.",
    "Your perspective can turn problems into possibilities.",
    "Not every door is locked---some just need a push.",
    "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
    "Your perception shapes your reality.",
    "You can’t control the wind, but you can adjust your sails.",
    "Wisdom is knowing the difference between what you can control and what you must release.",
    "A wise person listens more than they speak.",
    "The truth will always surface—don’t build on lies.",
    "Perspective can turn obstacles into opportunities.",
    "Don’t let temporary emotions create permanent damage.",
    "Your greatest teacher is your last mistake.",
    "Growth is painful. Staying the same is painful. Choose your pain.",
    "Wisdom is not knowing all the answers, but asking the right questions.",
    "A wise person listens more than they speak.",
    "True wisdom comes not from age, but from understanding.",
    "Knowledge is knowing what to say, wisdom is knowing when to say it.",
    "Wisdom is built from mistakes, not from perfection.",
    "A fool seeks to be right, a wise person seeks to understand.",
    "The greatest lessons in life often come disguised as failures.",
    "Wisdom is knowing when to walk away and when to stand your ground.",
    "The strongest minds are those that remain open.",
    "The more wisdom you gain, the less you need to prove yourself.",
    "A wise person is slow to judge, quick to learn, and eager to grow.",
    "Silence often speaks louder than words—wisdom knows when to use it.",
    "Patience is the companion of wisdom.",
    "A wise heart is more valuable than a full mind.",
    "You don’t have to have all the answers to be wise, just the willingness to learn.",
    "The greatest wisdom is found in the simplest truths.",
    "Being wise doesn’t mean avoiding mistakes, but learning from them.",
    "Humility is the foundation of wisdom.",
    "Wisdom isn’t about being right—it’s about seeing beyond right and wrong.",
    "A wise person grows from criticism, while a fool rejects it.",
    "Your world is shaped not by what you see, but by how you choose to see it.",
    "Two people can see the same sunset and describe it differently—perspective is everything.",
    "Changing your perspective can change your entire reality.",
    "Your mindset is the lens through which you experience life—choose it wisely.",
    "The same storm that destroys one person can strengthen another.",
    "Sometimes, the only thing standing between you and happiness is a shift in perspective.",
    "What seems like the end may just be a new beginning.",
    "Every challenge carries a lesson—look for it.",
    "Don’t let small moments of frustration cloud a lifetime of blessings.",
    "Your thoughts shape your world more than circumstances ever could.",
    "A problem is only as big as the way you see it.",
    "Sometimes stepping back reveals the bigger picture you couldn’t see up close.",
    "The way you see others is often a reflection of yourself.",
    "The beauty of life lies in how you choose to interpret it.",
    "Look at obstacles as opportunities in disguise.",
    "A shift in perspective can turn fear into excitement, and doubt into possibility.",
    "What you focus on grows—choose your perspective carefully.",
    "There are no ordinary moments—only perspectives that fail to see them.",
    "Nothing in life has meaning until you give it one.",
    "The world doesn’t change, but the way you see it can.",
    "Wisdom teaches that every experience has value if you look at it the right way.",
    "An open mind leads to wisdom; a fixed perspective leads to limitation.",
    "Sometimes, wisdom is simply seeing what others overlook.",
    "Perspective gives meaning, and wisdom gives direction.",
    "Growth happens when wisdom meets a new perspective.",
    "Wisdom is learning from the past; perspective is shaping the future.",
    "With wisdom, you understand. With perspective, you appreciate.",
    "The wisest people see every challenge as an opportunity to grow.",
    "What you know is wisdom; how you see it is perspective.",
    "A wise heart and a broad perspective make an unstoppable combination.",
    "Create more than you consume.",
    "Your imagination is your superpower---use it.",
    "Stop overthinking and start creating.",
    "Perfection is the enemy of progress---just start.",
    "Your creativity is a gift---don't waste it.",
    "Dare to be different---that's where brilliance is born.",
    "The best ideas are the ones that scare you.",
    "You don't need permission to create.",
    "Bold ideas change the world.",
    "Create something today that makes tomorrow better.",
    "Creativity is thinking outside the limits you've been given.",
    "Every problem is an opportunity in disguise.",
    "The best ideas come from those who dare to be different.",
    "Stop waiting for inspiration---start creating it.",
    "Creativity flourishes when you stop fearing judgment.",
    "Your vision is yours for a reason---pursue it.",
    "Bold ideas change the world.",
    "There is no innovation without risk.",
    "Perfection kills progress---just start.",
    "You don't need permission to create something extraordinary.",
    "Your ideas mean nothing without execution.",
    "Create more than you consume.",
    "The best ideas start as crazy ones.",
    "Innovation is thinking differently, then acting on it.",
    "Perfection kills progress---just start.",
    "Your unique vision is your greatest gift.",
    "Dare to stand out, or be forgotten.",
    "Creativity isn't a gift---it's a muscle. Train it.",
    "The world is shaped by those who take risks.",
    "Create something today that your future self will thank you for.",
    "The best ideas come when you stop overthinking.",
    "Creativity flourishes in action, not perfection.",
    "Every great innovation started as an 'impossible' idea.",
    "You don't need permission to create something great.",
    "Dare to think differently---greatness is in originality.",
    "Imperfect action beats perfect inaction every time.",
    "Your voice, your ideas, your vision---bring them to life.",
    "Success starts with a crazy idea and the courage to pursue it.",
    "If they doubt you, let your results do the talking.",
    "Dream wildly. Create boldly. Execute relentlessly.",
    "Creativity is not about being unique, but about seeing the ordinary in a new way.",
    "Your imagination is the birthplace of every great idea.",
    "Creativity flourishes in curiosity, not certainty.",
    "Art begins where rules end.",
    "The best ideas come when you stop searching for them.",
    "Creativity is seeing what others miss and turning it into something meaningful.",
    "Inspiration whispers—only those who listen carefully can hear it.",
    "Creativity isn’t a gift, it’s a muscle—use it or lose it.",
    "A blank page is not empty; it’s full of possibilities.",
    "Creativity doesn’t follow logic, it follows passion.",
    "An idea is just a seed; creativity is what makes it grow.",
    "True creativity thrives in the freedom to fail.",
    "Art is not about perfection, but about perspective.",
    "Creativity is not limited by resources, but by imagination.",
    "The best creative minds turn limitations into inspiration.",
    "Creativity is the bridge between what exists and what’s possible.",
    "Your best ideas often hide behind your biggest doubts.",
    "Great art is not made—it is discovered.",
    "Creativity is the courage to let your mind wander where others fear to go.",
    "Every masterpiece starts as a mess.",
    "Innovation isn’t about new ideas—it’s about making ideas work.",
    "The best innovations solve problems no one noticed before.",
    "An invention changes the world, but innovation changes how we live in it.",
    "Innovation happens when we challenge what’s ‘good enough.’",
    "The future belongs to those who create it.",
    "Breakthroughs begin where comfort zones end.",
    "Innovation is not about thinking outside the box—it’s about redefining the box itself.",
    "The biggest risk is refusing to evolve.",
    "Change doesn’t happen by waiting for permission.",
    "Innovation is fueled by the hunger for better.",
    "The best solutions often start as the wildest ideas.",
    "To innovate, first unlearn what limits you.",
    "Disruption isn’t destruction—it’s reinvention.",
    "Innovation happens when we stop asking ‘why’ and start asking ‘what if.’",
    "A true innovator is never satisfied with ‘that’s how it’s always been done.’",
    "If no one questions you, you’re not innovating hard enough.",
    "Every great innovation was once considered impossible.",
    "The most powerful tool for innovation is an open mind.",
    "Progress is impossible without the willingness to challenge tradition.",
    "Innovation is turning imagination into reality.",
    "Creativity imagines the future; innovation builds it.",
    "Creative minds dream—innovative minds do.",
    "An idea without execution is just imagination.",
    "Creativity sparks ideas; innovation turns them into impact.",
    "The best ideas are useless without action.",
    "Invention creates something new—innovation makes it useful.",
    "Imagination fuels creativity; persistence fuels innovation.",
    "The key to innovation is embracing the unknown.",
    "Great innovations often start as crazy ideas.",
    "Every innovation begins as a moment of creative curiosity.",
    "Without creativity, there is no innovation. Without innovation, creativity is wasted.",
    "A creative mind sees possibility; an innovative mind makes it real.",
    "The boldest ideas often come from the quietest moments.",
    "The magic of creativity lies in its unpredictability.",
    "To innovate is to create something the world didn’t know it needed.",
    "Creativity is the heartbeat of progress.",
    "Every new idea is a rebellion against the ordinary.",
    "Creative minds see problems as puzzles waiting to be solved.",
    "Innovation starts with a single ‘What if?’",
    "Creativity is the artist; innovation is the architect.",
    "Happiness isn't a destination; it's a choice.",
    "The richest person is the one who's content.",
    "Gratitude turns what you have into enough.",
    "A simple life is often the most fulfilling one.",
    "Happiness grows when shared.",
    "Real wealth is waking up with purpose.",
    "The best things in life aren't things.",
    "Choose joy, even when it's hard.",
    "Your peace is more valuable than their approval.",
    "Live in a way that makes your soul proud.",
    "Happiness is a daily practice, not a destination.",
    "Gratitude turns what you have into enough.",
    "The richest person isn't the one with the most money, but the most peace.",
    "A simple life is often the most fulfilling one.",
    "Peace is worth more than any paycheck.",
    "Find joy in the ordinary, and life becomes extraordinary.",
    "Happiness multiplies when shared.",
    "You don't need more---you need less distraction.",
    "Choose experiences over possessions.",
    "A fulfilled life is one lived with purpose.",
    "Joy is found in the present, not the past or future.",
    "Happiness is a mindset, not a destination.",
    "A rich life is measured in experiences, not possessions.",
    "What you appreciate grows---start with gratitude.",
    "True wealth is waking up excited for the day ahead.",
    "Fulfillment comes from contribution, not accumulation.",
    "Simplify your life, and you'll find more joy.",
    "Happiness is built, not found.",
    "Your energy introduces you before you speak---protect it.",
    "Live in a way that makes your soul proud.",
    "Joy is found in the present, not the past or future.",
    "Happiness is a skill, not a destination.",
    "Gratitude turns ordinary days into extraordinary ones.",
    "You don't need more to be happy; you need presence.",
    "Simplify to amplify your happiness.",
    "Fulfillment comes from progress, not perfection.",
    "A rich life is built on moments, not possessions.",
    "The best things in life aren't things.",
    "Find joy in the journey, not just the destination.",
    "Happiness multiplies when shared.",
    "Happiness isn’t a goal—it’s a byproduct of how you live.",
    "Peace isn’t found in the future—it’s built in the present.",
    "Joy is found in the small moments, not the big achievements.",
    "A life chasing happiness will always feel one step behind.",
    "Your best memories won’t be from what you achieved, but from who you shared them with.",
    "A fulfilled life is one that aligns with your values, not society’s expectations.",
    "Contentment is wealth.",
    "Simplicity is often the key to true happiness.",
    "You don’t need more to be happy. You need less of what drains you.",
    "A busy life isn’t always a fulfilling life.",
    "Happiness isn’t found in things, but in the moments we cherish.",
    "True happiness is not about having more, but appreciating what you already have.",
    "Happiness is not a destination, but a way of traveling through life.",
    "Joy is found in the present, not in the pursuit of the future.",
    "Happiness begins where comparison ends.",
    "A grateful heart is the key to lasting happiness.",
    "Happiness isn’t in perfection—it’s in embracing life as it is.",
    "The happiest people focus on what they can give, not just what they can get.",
    "Happiness is an inside job—don’t outsource it to circumstances.",
    "Smiling costs nothing but has the power to change everything.",
    "You don’t need a perfect life to be happy—just a perspective that allows you to see the beauty in it.",
    "Happiness grows when shared.",
    "A peaceful mind leads to a joyful heart.",
    "Happiness is not about the absence of problems, but the presence of perspective.",
    "Every day holds a small piece of happiness—you just have to notice it.",
    "The simplest things in life often bring the greatest joy.",
    "Surround yourself with people who make your soul feel lighter.",
    "Happiness isn’t about chasing the extraordinary, but appreciating the ordinary.",
    "Contentment is the foundation of happiness.",
    "The best way to be happy is to make someone else smile.",
    "Fulfillment comes not from what we accomplish, but from why we do it.",
    "A meaningful life is more fulfilling than a successful one.",
    "You don’t find fulfillment; you create it through purpose.",
    "A life well-lived is measured by impact, not achievements.",
    "Passion fuels happiness, but purpose fuels fulfillment.",
    "Fulfillment comes from knowing you’ve made a difference.",
    "Doing what you love is happiness; doing what matters is fulfillment.",
    "Chasing success without purpose leads to emptiness.",
    "When your work aligns with your values, fulfillment follows.",
    "The most rewarding paths are often the ones less traveled.",
    "Fulfillment isn’t in reaching the top—it’s in the climb.",
    "Your purpose isn’t found in what you do, but in how you do it.",
    "True fulfillment comes when passion and service meet.",
    "A full heart is worth more than a full bank account.",
    "Life’s greatest fulfillment comes from lifting others up.",
    "Success without fulfillment is an empty victory.",
    "Your dreams should be bigger than just yourself.",
    "The joy of creating is far greater than the satisfaction of possessing.",
    "A life of meaning leads to a life of fulfillment.",
    "Fulfillment is found in progress, not perfection.",
    "Happiness makes life brighter; fulfillment makes it deeper.",
    "A joyful life is one where passion and purpose walk together.",
    "Happiness is what you feel; fulfillment is what you leave behind.",
    "Live fully, love deeply, and purpose will follow.",
    "Happiness is the spark; fulfillment is the flame.",
    "Life is most beautiful when you love what you do and why you do it.",
    "A rich life isn’t about wealth—it’s about purpose, love, and laughter.",
    "The pursuit of happiness leads to moments of joy; the pursuit of purpose leads to a lifetime of fulfillment.",
    "Happiness is in being, fulfillment is in becoming.",
    "A truly fulfilling life is one that gives more than it takes.",
    "Your life's work is bigger than a paycheck.",
    "Impact outlives achievement.",
    "Make your existence count for something.",
    "If you woke up today, there's still work to do.",
    "Your purpose isn't found---it's built.",
    "Live for something greater than yourself.",
    "Your legacy is written in the lives you touch.",
    "You were made for more than mediocrity.",
    "Make every moment count.",
    "Leave the world better than you found it.",
    "You weren't born to just pay bills and die.",
    "Your purpose is found in what lights your soul on fire.",
    "Live in a way that future generations will thank you for.",
    "The greatest legacy is the impact you leave on others.",
    "Your purpose isn't found---it's created.",
    "You have something the world needs---don't hold back.",
    "Live with urgency---tomorrow isn't promised.",
    "Make every moment count.",
    "Your story could be someone's survival guide.",
    "Chase meaning, not just money.",
    "Your purpose isn't found---it's built.",
    "Impact outlives achievement.",
    "Make decisions your future self will respect.",
    "Live in a way that inspires others to do the same.",
    "What you give to the world comes back multiplied.",
    "Don't just exist---leave a mark.",
    "If you woke up today, there's still work to do.",
    "Your legacy is written in the lives you touch.",
    "You are the architect of your own story.",
    "Make your life the masterpiece it was meant to be.",
    "Your impact outlives your existence---make it meaningful.",
    "Live in a way that future generations will thank you for.",
    "The greatest legacy is the lives you've touched.",
    "Your purpose is found in what sets your soul on fire.",
    "Create something that echoes beyond your lifetime.",
    "Success is rented, and rent is due every day.",
    "If it was easy, everyone would have it.",
    "No one remembers the ideas you didn't execute.",
    "The grind is lonely, but the view is worth it.",
    "You weren't born to be mediocre.",
    "Work until your idols become your rivals.",
    "Nothing great was built in a comfort zone.",
    "Your dream doesn't work unless you do.",
    "Winners focus on progress, not excuses.",
    "Get obsessed with your growth.",
    "You weren’t born to pay bills and die—make it mean something.",
    "Your legacy is built in the quiet moments, not just the big ones.",
    "Purpose isn’t found—it’s created.",
    "What you leave behind matters more than what you take with you.",
    "Live in such a way that people feel your presence even in your absence.",
    "True wealth is measured in impact, not income.",
    "Make your life a story worth telling.",
    "A fulfilled life is one where you gave more than you took.",
    "Your greatest purpose is revealed when you serve something bigger than yourself.",
    "Live today as if your future self is watching.",
    "Your purpose isn’t something you find—it’s something you create.",
    "A life without purpose is like a journey without direction.",
    "Your purpose is hidden in what you love and who you help.",
    "Passion makes you excited; purpose makes you unstoppable.",
    "When you align with your purpose, every challenge becomes fuel.",
    "You were not born to merely exist, but to contribute something unique.",
    "Purpose gives pain a reason and success a meaning.",
    "If you don’t define your purpose, distractions will define it for you.",
    "The moment you serve something bigger than yourself, purpose is born.",
    "Your talents are not random; they are the keys to your purpose.",
    "The world doesn’t need more successful people—it needs more people living with purpose.",
    "True fulfillment comes when your work reflects your purpose.",
    "Your purpose isn’t just about what you do, but about who you become.",
    "The secret to a meaningful life is to align your actions with your values.",
    "You don’t have to change the world—just change the lives around you.",
    "Purpose is not a destination, but a way of walking through life.",
    "When you live with purpose, even the smallest actions have meaning.",
    "Clarity of purpose eliminates confusion and fuels determination.",
    "Some search for purpose; others create it from where they stand.",
    "Purpose is the bridge between where you are and where you’re meant to be.",
    "Your legacy is written not in what you leave behind, but in who you inspire.",
    "True legacy isn’t about wealth—it’s about wisdom shared and lives touched.",
    "What you build for yourself fades; what you build for others lasts.",
    "Your legacy is the echo of your kindness and the impact of your actions.",
    "A lasting legacy is not in monuments, but in the hearts you uplift.",
    "People won’t remember what you had, but how you made them feel.",
    "The best way to be remembered is to live in a way worth remembering.",
    "A meaningful legacy is crafted in the small, consistent acts of love.",
    "Your greatest legacy is the love and wisdom you pass forward.",
    "The footprints of your actions will outlast the shadow of your words.",
    "Every day, you write a chapter of the story people will tell about you.",
    "A true legacy isn’t measured in years, but in the difference made.",
    "What you teach others today becomes a ripple through time.",
    "Your name may fade, but your influence can live forever.",
    "Wealth disappears, but the impact of a kind heart never fades.",
    "Your legacy is the sum of the lives you lift up, not the titles you collect.",
    "The greatest legacies come from those who dared to serve.",
    "The stories others tell about you define the mark you leave behind.",
    "Make your life a message, not just a memory.",
    "A fulfilled life is one that leaves behind more than it takes.",
    "Purpose shapes your journey; legacy shapes how you’ll be remembered.",
    "A life of purpose naturally creates a legacy worth leaving.",
    "Your purpose drives today; your legacy inspires tomorrow.",
    "When you live on purpose, your legacy writes itself.",
    "A meaningful life is one where purpose and legacy walk hand in hand.",
  ];

  useEffect(() => {
    addDocuments(arr);
  }, []);

  const addDocuments = async (quotes) => {
    for (let i = 0; i < quotes.length; i++) {
      let category = "";

      if (i < 100) category = "self";
      else if (i < 200) category = "strength";
      else if (i < 300) category = "discipline";
      else if (i < 400) category = "fear";
      else if (i < 500) category = "leadership";
      else if (i < 600) category = "love";
      else if (i < 700) category = "wisdom";
      else if (i < 800) category = "creativity";
      else if (i < 900) category = "happiness";
      else category = "purpose";

      const quote = quotes[i];
      try {
        const docRef = await addDoc(collection(db, "quotes"), { quote, category });
        console.log(`Added quote with ID: ${docRef.id}`);
      } catch (error) {
        console.error("Error adding quote: ", error);
      }
    }
  };

  // Call the function with the collection name and data array

  return <h1 className="text-3xl font-bold">Hello world!</h1>;
}
